services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: bookhub-sql
    environment:
      - MSSQL_SA_PASSWORD=BookHub@12345
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - bookhub-network
    healthcheck:
      # تعديل خاص بـ SQL 2025 (إضافة -C للوثوق بالشهادة داخلياً)
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'BookHub@12345' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  bookhub-api:
    build: .
    container_name: bookhub-api-container
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BookHubDb;User Id=sa;Password=BookHub@12345;TrustServerCertificate=True;MultiSubnetFailover=True
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
    networks:
      - bookhub-network

networks:
  bookhub-network:
    driver: bridge